### ISSUE TITLE
vnstatd web-ui

### ISSUE THREAD

**Issue by mariusrugan** [carlosedp/rpi-media-server#2]
Issues are not enabled on the fork: https://github.com/carlosedp/docker-vnstatd so i'm opening it here:

First thanks for your work i found it very helpful; 
I found https://github.com/stnight/go-vnstat which is a UI to vnstat's data; Since it's Go and not PHP+libs/dependencies+webserver (https://github.com/Xalior/jsvnstat), would you be interested to merge it in the docker-vnstatd so we can have a UI to it ?

**Comment by carlosedp** [comment]
Can you build and test this locally in your deployment? I've migrated some of my nodes to Kubernetes and not using vnstat right now so I'm not able to merge this GUI into the container image.
If successful, please send a PR.

**Comment by mariusrugan** [comment]
Sure, asap;
